name: coffee2u
description: Coffee2U by Aroma

publish_to: 'none'

version: 9.0.3+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  shared_preferences:  ^2.5.2
  cached_network_image: ^3.4.1
  get: ^4.7.2
  timeago: ^3.2.2
  google_maps_flutter: ^2.12.0
  geolocator: ^13.0.3
  map_launcher:
    path: patched_plugins/map_launcher
  sliver_tools: ^0.2.12
  badges: ^3.1.2
  dotted_border: ^2.1.0
  introduction_screen: ^3.1.17
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0
  flutter_swiper_null_safety: ^1.0.2
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  percent_indicator: ^4.2.4
  flutter_svg: ^2.0.17
  hexagon: ^0.2.0
  steps_indicator: ^1.3.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  flutter_html: ^3.0.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  visibility_detector: ^0.4.0+2
  html_unescape: ^2.0.0
  timezone: ^0.10.0
  flutter_stripe: ^11.4.0
  pin_code_fields: ^8.0.1
  geocoding: ^3.0.0
  flutter_phoenix: ^1.1.1
  location:
    path: patched_plugins/location
  webview_flutter: ^4.10.0
  dio: ^5.8.0+1
  external_app_launcher: ^4.0.3
  in_app_review: ^2.0.10
  flutter_linkify: ^6.0.0
  go_router: ^14.8.1
  firebase_analytics: ^11.4.4
  app_tracking_transparency: ^2.0.6+1
  confetti: ^0.8.0
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.2.1
  palette_generator: ^0.3.3+6
  signature: ^6.0.0
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  app_links: ^6.4.0
  app_badge_plus: ^1.2.3
  
  # uni_links: ^0.5.1 // TODO
  # location: ^8.0.0 // TODO
  # map_launcher: ^3.5.0 // TODO
  # flutter_localization: ^0.3.1
  # intl: any
  
  # image_gallery_saver: ^2.0.3
  # uni_links5: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env_DEV
    - .env_DEV_UAT
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/banner/
    - assets/images/promotion/
    - assets/images/payments/
    - assets/icons/tier/
    - assets/icons/payment/
    - assets/lang/
    - assets/data/
    - assets/default/
    - assets/images/flag/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/kanit/Kanit-Thin.ttf
          weight: 100
        - asset: assets/fonts/kanit/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/kanit/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/kanit/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/kanit/Kanit-SemiBold.ttf
          weight: 600
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/century_gothic/CenturyGothic-Regular.ttf
        - asset: assets/fonts/century_gothic/CenturyGothic-Bold.TTF
          weight: 600
