// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /* ==================================================== 
                            UAT
     ==================================================== */
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDr6VPnZnkQAJmXBp2FqrOCjPyzzCIcXTo',
  //   appId: '1:51335720777:ios:0f8a29124ddade65593498',
  //   messagingSenderId: '100945625585',
  //   projectId: 'coffee2u-dev',
  //   storageBucket: 'coffee2u-dev.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDr6VPnZnkQAJmXBp2FqrOCjPyzzCIcXTo',
  //   appId: '1:51335720777:ios:0f8a29124ddade65593498',
  //   messagingSenderId: '51335720777',
  //   projectId: 'coffee2u-dev',
  //   storageBucket: 'coffee2u-dev.appspot.com',
  //   androidClientId: '100945625585-1suisehdtornh0s3oki09vq2pkgrqvga.apps.googleusercontent.com',
  //   iosClientId: '100945625585-th7hakqsrr990b6vubqkctrf971o0p9t.apps.googleusercontent.com',
  //   iosBundleId: 'com.coffee2u.aroma',
  // );


  /* ==================================================== 
                      PRODUCTION
     ==================================================== */
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KokZvAfNfXz1EHZNIYa4HHMz_4njt5c',
    appId: '1:100945625585:android:e5b2b18a4d5292685fc450',
    messagingSenderId: '100945625585',
    projectId: 'coffee2u-cfac1',
    storageBucket: 'coffee2u-cfac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2KokZvAfNfXz1EHZNIYa4HHMz_4njt5c',
    appId: '1:100945625585:ios:2a5ffa8764c54fde5fc450',
    messagingSenderId: '100945625585',
    projectId: 'coffee2u-cfac1',
    storageBucket: 'coffee2u-cfac1.appspot.com',
    androidClientId: '100945625585-1suisehdtornh0s3oki09vq2pkgrqvga.apps.googleusercontent.com',
    iosClientId: '100945625585-th7hakqsrr990b6vubqkctrf971o0p9t.apps.googleusercontent.com',
    iosBundleId: 'com.coffee2u.aroma',
  );
}